---
  - name: Create Feature Template
    uri:
      url: https://{{ansible_host}}:{{ansible_port}}/dataservice/device
      method: GET
      return_content: yes
      validate_certs: no
      body_format: json
      headers:
        Cookie: "{{login.set_cookie}}"
        Content-Type: "application/json"
    register: test123 

  - name: Print content
    debug: var=test123
#  with_fileglob:
#    - "{{ role_path }}/files/*.json"
