- name: CiscoDevNet SDWAN Ansible Learning Lab 1
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Login to the vManage
      uri:
        url: https://{{ansible_host}}:{{ansible_port}}/dataservice/j_security_check
        method: POST
        body: "j_username={{username}}&j_password={{password}}"
        validate_certs: no
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: login

    - name: Generate all template list
      uri:
        url: https://{{ansible_host}}:{{ansible_port}}/dataservice/template/policy/vsmart
        method: GET
        return_content: yes
        validate_certs: no
        body_format: json
        headers:
          Cookie: "{{login.set_cookie}}"
          Content-Type: "application/json"
        body:
          isPolicyActivated: true
      register: test123 
